#ifndef HID_IDS_H_FILE
#define HID_IDS_H_FILE

#define USB_VENDOR_ID_AERO_WIRELESS 0x248a
#define USB_DEVICE_ID_AERO_WIRELESS_MOUSE_C 0xfb01
#define USB_DEVICE_ID_AERO_WIRELESS_MOUSE_W 0xfa02

#endif
